force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initialization</fullName>
    </customValue>
    <customValue>
        <fullName>Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectStageBatch.cls
global class ProjectStageBatch implements Database.Batchable<SObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
            return Database.getQueryLocator([
                SELECT Id, Stage__c, Due_Date__c FROM Project__c WHERE Due_Date__c < :Date.today()
            ]);
    }
        
    global void execute(Database.BatchableContext BC, List<Project__c> scope) {
        ProjectUtils.projectStageOnHold(scope);
    }
        
    global void finish(Database.BatchableContext BC) {
        System.debug('Batch job for updating projects completed.');
    }
}