force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Remaining_Budget__c.field-meta.xml
<CustomField>
    <fullName>Remaining_Budget__c</fullName>
    <formula>Budget__c -  Spent_Budget__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remaining Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task_Template__c/Task_Template__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task_Template__c/fields/Cost_Of_Activity__c.field-meta.xml
<CustomField>
    <fullName>Cost_Of_Activity__c</fullName>
    <label>Cost Of Activity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Task_Template__c/fields/Execution_Time__c.field-meta.xml
<CustomField>
    <fullName>Execution_Time__c</fullName>
    <label>Execution Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initialization</fullName>
    </customValue>
    <customValue>
        <fullName>Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectTriggerHelper.cls
public with sharing class ProjectTriggerHelper {
    public static void onStageChangeCreateTasks(List<Project__c> newProjects, Map<Id, Project__c> oldProjectsMap) {
        List<Task> tasksToCreate = new List<Task>();
        Set<String> newStages = new Set<String>();
        for (Project__c newProject : newProjects) {
            Project__c oldProject = oldProjectsMap.get(newProject.Id);
            if (newProject.Stage__c != oldProject.Stage__c) {
                newStages.add(newProject.Stage__c);
            }
        }
        List<Task_Template__c> taskTemplates = [
            SELECT Name, Stage__c, Priority__c, Cost_Of_Activity__c, Execution_Time__c 
            FROM Task_Template__c 
            WHERE Stage__c IN :newStages
        ];
        Map<String, List<Task_Template__c>> stageToTaskTemplates = new  Map<String, List<Task_Template__c>>();
        for (Task_Template__c taskTemplate : taskTemplates) {
            if(!stageToTaskTemplates.containsKey(taskTemplate.Stage__c)) {
                stageToTaskTemplates.put(taskTemplate.Stage__c, new List<Task_Template__c>());
            }
            stageToTaskTemplates.get(taskTemplate.Stage__c).add(taskTemplate);

        }

        for (Project__c newProject : newProjects) {
            Project__c oldProject = oldProjectsMap.get(newProject.Id);
            if (newProject.Stage__c != oldProject.Stage__c) {
                List<Task_Template__c> taskTemplatesForCurrentProjectStage = stageToTaskTemplates.get(newProject.Stage__c);
                for (Task_Template__c taskTemplate: taskTemplatesForCurrentProjectStage) {
                    
                    Task newTask = new Task();
                    newTask.WhatId = newProject.Id;
                    if (String.isBlank(taskTemplate.Priority__c)) {
                        newTask.Priority = 'Low';
                    } else {
                        newTask.Priority = taskTemplate.Priority__c;
                    }
                    if (String.isBlank(newProject.Project_Manager__c)) {
                        newTask.OwnerId = UserInfo.getUserId();
                    } else {
                        newTask.OwnerId = newProject.Project_Manager__c;
                    }
                    newTask.Cost_Of_Activity__c = taskTemplate.Cost_Of_Activity__c;
                    newTask.Subject = taskTemplate.Name;
                    if (taskTemplate.Execution_Time__c != null) {
                        Integer dueDays = taskTemplate.Execution_Time__c.intValue();
                        newTask.ActivityDate = Date.Today().addDays(dueDays);
                    }
                    tasksToCreate.add(newTask);
                } 
                     
            }
            
        }
    
        // Insert tasks if any were created
        if (!tasksToCreate.isEmpty()) {
            try {
                insert tasksToCreate;
                System.debug('Tasks Created Successfully');
            } catch (DmlException e) {
                System.debug('Error creating tasks from templates: ' + e.getMessage());
            }
        } else {
            System.debug('No tasks to create.');
        }
    }
    
    
    public static void sendBudgetExceedEmails(List<Project__c> newProjects, Map<Id, Project__c> oldProjectsMap) {
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        EmailTemplate emailTemplate = [SELECT Id, Subject, Body, HtmlValue FROM EmailTemplate WHERE Name = 'Project_Budget_Exceed_Notification'];

        for (Project__c newProject : newProjects) {
            Project__c oldProject = oldProjectsMap.get(newProject.Id);
            
           
            if (newProject.Remaining_Budget__c < 0) {
                
                if (newProject.Project_Manager__c != null) {
                    Messaging.SingleEmailMessage email = Messaging.renderStoredEmailTemplate(emailTemplate.Id, newProject.OwnerId, newProject.Id);
                    email.setTargetObjectId(newProject.Project_Manager__c);
                    email.setTemplateId(emailTemplate.Id);
                    email.setWhatId(newProject.Id);
                    email.setSaveAsActivity(false);
                    
                    emails.add(email);
                }
            }
        }

        if (!emails.isEmpty()) {
            try {
                Messaging.sendEmail(emails);
                System.debug('Budget exceed emails sent successfully.');
            } catch (DmlException e) {
                System.debug('Error sending budget exceed emails: ' + e.getMessage());
            }
        }
    }
}