force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Spent_Budget__c.field-meta.xml
<CustomField>
    <fullName>Spent_Budget__c</fullName>
    <label>Spent Budget</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initialization</fullName>
    </customValue>
    <customValue>
        <fullName>Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
public with sharing class TestDataFactory {
    public static List<Account> createAccount(Integer numberOfAccounts, String Type) {
        List<Account> accounts = new List<Account>();
        for(Integer i=0; i<numberOfAccounts; i++) {
            Account acc = new Account();
            acc.Name = 'Thomas' + i;
            acc.Type = Type;
            accounts.add(acc);
        }
        insert accounts;
        return accounts;
    }

    public static Project__c createTestProjectForStage(Date dueDate, String initialStage) {
        Account client = [SELECT Id,Type FROM Account LIMIT 1];
        Project__c project = new Project__c(Name = 'Test Project', Due_Date__c = dueDate, Stage__c = initialStage, Client__c = client.Id);
        insert project;
        return project;
    }
    public static Project__c createTestProjectForSpentBudget(Decimal budget, Decimal spentBudget) {
        Account client = [SELECT Id,Type FROM Account LIMIT 1];
        Project__c project = new Project__c(Name = 'Test Project', Budget__c = budget, Spent_Budget__c = spentBudget,Client__c = client.Id);
        insert project;
        return project;
    }
    public static Task createTestTask(Id projectId, String status, Decimal costOfActivity) {
        Task task = new Task(WhatId = projectId, Status = status, Cost_Of_Activity__c = costOfActivity, Subject = 'Test Task');
        insert task;
        return task;
    }
    public static Task createTestTaskForUser(Id projectId, String status, Decimal costOfActivity, Id projectManagerId) {
        Task task = new Task(WhatId = projectId, Status = status, Cost_Of_Activity__c = costOfActivity, Subject = 'Test Task', OwnerId = projectManagerId);
        insert task;
        return task;
    }
}