force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Initialization</fullName>
    </customValue>
    <customValue>
        <fullName>Preparation</fullName>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>On Hold</fullName>
    </customValue>
    <customValue>
        <fullName>Completed</fullName>
    </customValue>
    <masterLabel>Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectSendEmailBatch.cls
global class ProjectSendEmailBatch implements Database.Batchable<SObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT Id, Name, Due_Date__c, Stage__c, Project_Manager__r.Name, Owner.Name, RecordType.Name,RecordType.DeveloperName
            FROM Project__c
            WHERE Due_Date__c < :Date.today()
        ]);
    }

    global void execute(Database.BatchableContext BC, List<Project__c> scope) {
    
        ProjectUtils.sendOverdueProjectsEmail(scope);
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('Monthly overdue projects email batch job completed.');
    }
}
    